name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        go: [ 1.17 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...
